include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options_prod.dart"
    - "**/firebase_options_stg.dart"
linter:
  rules:
    constant_identifier_names: false
