name: my_sns_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  freezed_annotation:
  json_annotation:
  go_router:
  flutter_riverpod:
  bubble_lens:

  # firebase
  firebase_core:
  cloud_firestore:
  badges:
  flutter_dotenv:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  device_preview:
  pedantic_mono:

flutter:
  uses-material-design: true
  assets:
    - .env
